### ISSUE TITLE
KeyError: 'pushover'

### ISSUE THREAD

**Issue by GarrickLin** [amirfefer/Cyber-Camera#10]
I am running this project on 64bit Windows10. After installing dependency, it raised this error:
```
> python server.py
Traceback (most recent call last):
  File "server.py", line 22, in <module>
    cmra = camera.VideoCamera(conf)
  File "D:\GK\WorkSpace\Code\Python\tools\Cyber-Camera\camera.py", line 22, in __init__
    self.notification = notifications.Notification(config)
  File "D:\GK\WorkSpace\Code\Python\tools\Cyber-Camera\notifications.py", line 7, in __init__
    self.user = conf.get('Notifications')['pushover']
KeyError: 'pushover'
```
Could you tell what's going wrong with it ?

**Comment by amirfefer** [comment]
Hi @GreenKing, Did you fill out the `config.ini` file? 
You can follow up the documentation [here](https://github.com/amirfefer/Cyber-Camera/wiki/How-to-configure%3F) 

I've pushed a [fix](https://github.com/amirfefer/Cyber-Camera/commit/85a82cc3df82f8445f791b2f5326776f4cf70688) for this issue.
