### ISSUE TITLE
username and password

### ISSUE THREAD

**Issue by mrafsyam** [amirfefer/Cyber-Camera#12]
I set the username in conf.ini to **raf** and generate sha224 for it.

Entering those details on the url, ive got 

![screenshot from 2018-04-24 00-58-29](https://user-images.githubusercontent.com/6120781/39141599-d1c48120-475a-11e8-9e39-501b3a26140f.png)

Did I miss something?

**Comment by amirfefer** [comment]
Hello @mrafsyam!
A long time has been passed, but I wouldn't close this without an answer :)
The credentials should be filled like this:
```ini
raf = SAH224(<YOUR_PASSWORD>)
```
NOT like
```ini
username = raf
password = SAH224(<YOUR_PASSWORD>)
```
Though I do think the latter is much more readable :+1: 
Hopefully, this will fix your issue, if not please open a follow-up issue.
